env_path = [
  ".venv/bin"
]

[tools]
poetry = "1.6.1"
minikube = "1.31.2"

[env]
# poetry
POETRY_ACTIVE="true"
POETRY_VIRTUALENVS_PATH=".venv"
VIRTUAL_ENV=".venv"

# rtx
RTX_EXPERIMENTAL="true"
RTX_FETCH_REMOTE_VERSIONS_TIMEOUT="30s"

# Vagrant
VAGRANT_CHECKPOINT_DISABLE="true"
VAGRANT_INSTALL_LOCAL_PLUGINS="true"
