[tool.poetry]
name = "cc.chroni.ansible"
version = "0.1.0"
description = ""
authors = ["Thomas Steinert <hello@chroni.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ansible = "^7.1.0"
docker = "^6.0.1"

[tool.poetry.dev-dependencies]
molecule = "^4.0.4"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
