collections:
  - name: community.docker
    version: 3.3.1
  - name: community.general
    version: 7.4.0

roles:
  - name: chronicc.bash
    version: 0.1.3
  - name: cimon-io.asdf
    version: v1.1.0
  - name: ctorgalson.nerdfonts
    version: v1.0.1
  - name: geerlingguy.docker
    version: 6.2.0
  - name: derJD.journald
    version: 0.0.1
