---
- name: geerlingguy.java
  version: 1.10.0
- name: lrk.sonarqube
  # version: v1.1.1
  # src: https://github.com/lrk/ansible-role-sonarqube.git
- name: lrk.sonarqube
  version: master
  src: https://github.com/chronicc/ansible-role-sonarqube.git
- name: kevincoakley.postgres
  version: 12.4.0
