---
- name: baserow // Create service directory
  ansible.builtin.file:
    dest: "{{ f_docker__home }}/baserow"
    state: directory
    owner: root
    group: docker
    mode: "0755"

- name: baserow // Create docker-compose.yml
  ansible.builtin.template:
    src: templates/baserow-docker-compose.yml.j2
    dest: "{{ f_docker__home }}/baserow/docker-compose.yml"
    owner: root
    group: docker
    mode: "0644"

- name: baserow // Update deployment
  community.docker.docker_compose_v2:
    project_src: "{{ f_docker__home }}/baserow"
