---
- name: kimai // Create service directory
  ansible.builtin.file:
    dest: "{{ f_docker__home }}/kimai"
    state: directory
    owner: root
    group: docker
    mode: "0755"
  tags:
    - application
    - kimai

- name: kimai // Create docker-compose.yml
  ansible.builtin.template:
    src: templates/kimai-docker-compose.yml.j2
    dest: "{{ f_docker__home }}/kimai/docker-compose.yml"
    owner: root
    group: docker
    mode: "0644"
  tags:
    - application
    - kimai

- name: kimai // Update deployment
  community.docker.docker_compose:
    project_src: "{{ f_docker__home }}/kimai"
  tags:
    - application
    - kimai
