---
- name: loki // Create service directory
  ansible.builtin.file:
    dest: "{{ f_docker__home }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - loki
    - loki/config

- name: loki // Write loki config
  ansible.builtin.template:
    src: templates/config/loki.local-config.yml.j2
    dest: "{{ f_docker__home }}/loki/config/loki.local-config.yml"
    owner: root
    group: root
    mode: "0644"
  notify: Restart loki

- name: loki // Write promtail config
  ansible.builtin.template:
    src: templates/config/promtail.config.yml.j2
    dest: "{{ f_docker__home }}/loki/config/promtail.yml"
    owner: root
    group: root
    mode: "0644"
  notify: Restart loki

- name: loki // Write promtheus config
  ansible.builtin.template:
    src: templates/config/prometheus.yml.j2
    dest: "{{ f_docker__home }}/loki/config/prometheus.yml"
    owner: root
    group: root
    mode: "0644"
  notify: Restart loki

- name: loki // Create docker-compose.yml
  ansible.builtin.template:
    src: templates/loki-docker-compose.yml.j2
    dest: "{{ f_docker__home }}/loki/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"

- name: loki // Update deployment
  community.docker.docker_compose:
    project_src: "{{ f_docker__home }}/loki"
