---
- name: matrixhook // Create service directory
  ansible.builtin.file:
    dest: "{{ f_docker__home }}/matrixhook"
    state: directory
    owner: root
    group: docker
    mode: "0755"

- name: matrixhook // Create docker-compose.yml
  ansible.builtin.template:
    src: templates/matrixhook-docker-compose.yml.j2
    dest: "{{ f_docker__home }}/matrixhook/docker-compose.yml"
    owner: root
    group: docker
    mode: "0644"

- name: matrixhook // Update deployment
  community.docker.docker_compose:
    project_src: "{{ f_docker__home }}/matrixhook"
