---
- name: mattermost-server // Create service directory
  ansible.builtin.file:
    dest: "{{ f_docker__home }}/mattermost"
    state: directory
    owner: root
    group: docker
    mode: "0755"

- name: mattermost-server // Create docker-compose.yml
  ansible.builtin.template:
    src: templates/mattermost-docker-compose.yml.j2
    dest: "{{ f_docker__home }}/mattermost/docker-compose.yml"
    owner: root
    group: docker
    mode: "0644"

- name: mattermost-server // Update deployment
  community.docker.docker_compose:
    project_src: "{{ f_docker__home }}/mattermost"
