---
- name: minecraft // Create service directory
  ansible.builtin.file:
    dest: "{{ f_docker__home }}/minecraft"
    state: directory
    owner: root
    group: docker
    mode: "0755"

- name: minecraft // Create docker-compose.yml
  ansible.builtin.template:
    src: templates/minecraft-docker-compose.yml.j2
    dest: "{{ f_docker__home }}/minecraft/docker-compose.yml"
    owner: root
    group: docker
    mode: "0644"

- name: minecraft // Update deployment
  community.docker.docker_compose:
    project_src: "{{ f_docker__home }}/minecraft"
