---
- name: roundcube // Create service directory
  ansible.builtin.file:
    dest: "{{ f_docker__home }}/roundcube"
    state: directory
    owner: root
    group: docker
    mode: "0755"
  tags:
    - application
    - roundcube

- name: roundcube // Create docker-compose.yml
  ansible.builtin.template:
    src: templates/roundcube-docker-compose.yml.j2
    dest: "{{ f_docker__home }}/roundcube/docker-compose.yml"
    owner: root
    group: docker
    mode: "0644"
  tags:
    - application
    - roundcube

- name: roundcube // Create nginx config for proxy container
  ansible.builtin.template:
    src: templates/roundcube-nginx.conf.j2
    dest: "{{ f_docker__home }}/roundcube/nginx.conf"
    owner: root
    group: root
    mode: "0644"
  tags:
    - application
    - roundcube

- name: roundcube // Update deployment
  community.docker.docker_compose:
    project_src: "{{ f_docker__home }}/roundcube"
  tags:
    - application
    - roundcube
