---
- name: valheim // Create service directory
  ansible.builtin.file:
    dest: "{{ f_docker__home }}/valheim"
    state: directory
    owner: root
    group: docker
    mode: "0755"

- name: valheim // Create docker-compose.yml
  ansible.builtin.template:
    src: templates/valheim-docker-compose.yml.j2
    dest: "{{ f_docker__home }}/valheim/docker-compose.yml"
    owner: root
    group: docker
    mode: "0644"

- name: valheim // Update deployment
  community.docker.docker_compose:
    project_src: "{{ f_docker__home }}/valheim"
