#!/usr/bin/env bash
# shellcheck disable=SC2154
# mise description="Install project dependencies"
# mise depends=["ansible:install"]

cd "$root" || exit 1

if [ ! -f .vscode/settings.json ]
then
    echo "No .vscode/settings.json found, copying from mise template."
    mkdir -p .vscode
    cp .mise/templates/settings.json .vscode/settings.json
fi
