ssh_authorized_keys_file: authorized_keys
ssh_enable: true
ssh_server_config_file: sshd_config
ssh_options:
  AcceptEnv: "LANG LC_*"
  KbdInteractiveAuthentication: "no"
  PasswordAuthentication: "no"
  PermitRootLogin: "yes"
  Port: "22"
  PrintMotd: "no"
  Subsystem: "sftp	/usr/lib/openssh/sftp-server"
  UsePAM: "yes"
  X11Forwarding: "no"

ssh_public_keys: []
