---
- name: docker // Add docker repository key
  ansible.builtin.apt_key:
    url: "{{ docker_repository_key_url }}"
    state: present

- name: docker // Add docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_repository }}"
    filename: docker
    state: present

- name: docker // Install docker package
  ansible.builtin.package:
    name: "{{ docker_package }}"
    state: present

- name: docker // Install docker python package
  ansible.builtin.pip:
    name: docker
    state: present

- name: docker // Install docker-compose python package
  ansible.builtin.pip:
    name: "docker-compose=={{ f_docker__compose_version }}"
    state: present

- name: docker // Create docker directories
  ansible.builtin.file:
    dest: "{{ item.path }}"
    state: directory
    owner: root
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ f_docker__home }}"
      group: docker
      mode: "0750"
    - path: /etc/docker
      group: root
      mode: "0755"

- name: docker // Write docker daemon config
  ansible.builtin.template:
    src: templates/config/docker.daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify: Restart docker
