sshd_options:
  AcceptEnv: "LANG LC_*"
  KbdInteractiveAuthentication: "no"
  PasswordAuthentication: "no"
  PermitRootLogin: "yes"
  Port: "22"
  PrintMotd: "no"
  Subsystem: "sftp	/usr/lib/openssh/sftp-server"
  UsePAM: "yes"
  X11Forwarding: "no"

sshd_config_file: sshd_config

sshd_enable: yes
