---
- name: Set hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'

- name: Ensure global packages are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop: '{{ common_packages }}'

- name: Ensure group specific packages are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop: '{{ common_group_packages }}'

- name: Ensure host specific packages are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop: '{{ common_host_packages }}'
