---
- name: Set hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'

- name: Set domainname
  ansible.builtin.cmd:
    cmd: '{{ common_domain_binary }} {{ inventory_domain }}'
  when: inventory_domainname is defined

- name: Ensure blacklisted packages are uninstalled
  ansible.builtin.package:
    name: '{{ item }}'
    state: absent
  loop: '{{ common_blacklisted_packages }}'

- name: Ensure global packages are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop: '{{ common_packages }}'

- name: Ensure group specific packages are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop: '{{ common_group_packages }}'

- name: Ensure host specific packages are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop: '{{ common_host_packages }}'
