---
init_pip_packages:
  - github3.py # required by community.general.github_release
  - passlib

init_python_packages:
  - python3-pip
  - python3-setuptools
  - python3.12
  - python3.12-minimal
  - python3.12-venv
