---
- name: Converge
  hosts: all
  vars:
    inventory_domain: example.com
  pre_tasks:
    - name: Ensure hosts file is unmounted
      ansible.posix.mount:
        path: /etc/hosts
        state: unmounted

    - name: Check hosts file content
      ansible.builtin.command: cat /etc/hosts
      changed_when: false
      register: _hosts_file

    - name: Write a basic hosts file
      ansible.builtin.copy:
        dest: /etc/hosts
        content: |
          127.0.0.1 localhost
          127.0.1.1 hostname

          # The following lines are desirable for IPv6 capable hosts
          ::1     ip6-localhost ip6-loopback
          fe00::0 ip6-localnet
          ff00::0 ip6-mcastprefix
          ff02::1 ip6-allnodes
          ff02::2 ip6-allrouters
        mode: '0644'
      when: _hosts_file.stdout == ''

  roles:
    - role: common
