---
- name: Configure all servers.
  hosts: servers
  become: yes
  serial: 10
  pre_tasks:
    - name: Include OS-specific variables
      ansible.builtin.include_vars: '{{ item }}'
      with_first_found:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
      tags:
        - always

  roles:
    - role: derJD.journald
      tags:
        - journal

  tasks:

    # ---( Features )---

    # Don't use the geerlinguy.docker here since docker-compose
    # needs to be installed with pip for the docker_compose module to work.
    - name: Import docker (Linux)
      ansible.builtin.import_tasks:
        file: features/docker_linux.yml
      when:
        - ansible_system == 'Linux'
        - feature_docker | default(false)
      tags:
        - docker

    - name: Include host git packages (Linux)
      ansible.builtin.include_tasks: features/host_git_packages.yml
      loop: '{{ h_git_packages | default([]) }}'
      when:
        - ansible_system == 'Linux'
      tags:
        - host

    - name: Import nginx (Linux)
      ansible.builtin.import_tasks:
        file: features/nginx.yml
      when:
        - ansible_system == 'Linux'
        - feature_nginx | default(false)
      tags:
        - application
        - nginx

    - name: Import traefik (Linux)
      ansible.builtin.import_tasks:
        file: features/traefik.yml
      when:
        - ansible_system == 'Linux'
        - feature_traefik | default(false)
      tags:
        - application
        - traefik

    # ---( Applications )---

    - name: Import baserow
      ansible.builtin.import_tasks:
        file: applications/baserow.yml
      when:
        - app_baserow | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - baserow

    - name: Import kimai
      ansible.builtin.import_tasks:
        file: applications/kimai.yml
      when:
        - app_kimai | default(false)
        - feature_docker | default(false)
        - (feature_nginx | default(false) or feature_traefik | default(false))
      tags:
        - application
        - kimai

    - name: Import loki
      ansible.builtin.import_tasks:
        file: applications/loki.yml
      when:
        - app_loki | default(false)
        - feature_docker | default(false)
        - (feature_nginx | default(false) or feature_traefik | default(false))
      tags:
        - application
        - loki

    - name: Import matrixhook
      ansible.builtin.import_tasks:
        file: applications/matrixhook.yml
      when:
        - app_matrixhook | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - matrixhook

    - name: Import mattermost-server
      ansible.builtin.import_tasks:
        file: applications/mattermost-server.yml
      when:
        - app_mattermost_server | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - mattermost-server

    - name: Import kuchen.cafe
      ansible.builtin.import_tasks:
        file: applications/kuchen.cafe.yml
      when:
        - app_kuchen_cafe | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - kuchen.cafe

    - name: Import nextcloud
      ansible.builtin.import_tasks:
        file: applications/nextcloud.yml
      when:
        - app_nextcloud | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - nextcloud

    - name: Import roundcube
      ansible.builtin.import_tasks:
        file: applications/roundcube.yml
      when:
        - app_roundcube | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - roundcube

    - name: Import teamspeak-server
      ansible.builtin.import_tasks:
        file: applications/teamspeak-server.yml
      when:
        - app_teamspeak_server | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - teamspeak-server

    - name: Import valheim
      ansible.builtin.import_tasks:
        file: applications/valheim.yml
      when:
        - app_valheim | default(false)
        - feature_docker | default(false)
      tags:
        - application
        - valheim

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      tags:
        - application
        - nginx

    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
      tags:
        - docker

    - name: Restart loki
      community.docker.docker_compose:
        project_src: '{{ f_docker__home }}/loki'
        restarted: yes
      tags:
        - application
        - loki
