---
- name: Configure linux workstations
  hosts: workstations
  become: yes
  serial: 10

  pre_tasks:
    - name: Fail when not running on linux
      ansible.builtin.fail:
        msg: 'This playbook is only intended to run on linux'
      when: ansible_system != 'Linux'
      tags:
        - always

    - name: Include OS-specific variables
      ansible.builtin.include_vars: '{{ item }}'
      with_first_found:
        - files:
            - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
            - '{{ ansible_distribution }}.yml'
          paths:
            - ../vars
      tags:
        - always

  roles:
    - role: common
      tags: common
    - role: cimon-io.asdf
      tags: asdf
    - role: chronicc.bash
      tags: bash
    - role: geerlingguy.docker
      tags: docker

  tasks:
    - name: Include host git packages (Linux)
      ansible.builtin.include_tasks: features/host_git_packages.yml
      loop: '{{ h_git_packages | default([]) }}'
      when:
        - ansible_system == 'Linux'
      tags:
        - host

    - name: Import android studio tasks
      ansible.builtin.import_tasks:
        file: features/android_studio_linux.yml
      when:
        - feature_android_studio | default(false)
      tags:
        - android-studio

    - name: Import flutter tasks
      ansible.builtin.import_tasks:
        file: features/flutter_linux.yml
      when:
        - feature_flutter | default(false)
      tags:
        - flutter

    - name: Import pyenv tasks
      ansible.builtin.import_tasks:
        file: features/pyenv_linux.yml
      when:
        - feature_pyenv | default(false)
      tags:
        - pyenv
