---
- name: Setup a minecraft server.
  hosts: all
  become: true
  serial: 10
  pre_tasks:
    - name: Include OS-specific variables.
      ansible.builtin.include_vars: '{{ item }}'
      with_first_found:
        - files:
            - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
            - '{{ ansible_distribution }}.yml'
          paths:
            - ../vars
      tags:
        always

  tasks:
    - name: Import docker (Linux)
      ansible.builtin.import_tasks:
        file: features/docker_linux.yml
      when:
        - ansible_system == 'Linux'
      tags:
        - docker

    - name: Import minecraft tasks.
      ansible.builtin.import_tasks:
        file: applications/minecraft-server.yml
      when:
        - ansible_system == 'Linux'
      tags:
        - application
        - minecraft

  handlers:
    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
      tags:
        - docker
