# Zabbix Server Single Host Setup
#
# Postgresql Debugging
# --------------------
# - Show list of users: \du or \du+
# - Show list of tablespaces: \db or \db+
# - Show list of databases: \l or \l+
# - Show list of tables: \dt
# - Connect to a database: \c <name>
# - Delete a database: DROP DATABASE <name> <options>;
# - Delete a table: DROP TABLE <name> <options>; (must be connected to database)
# - Revoke privileges of a user: DROP OWNED BY <name>; (must be connected to database)
# - Delete a user: DROP USER <name> <options>;
#
# Apache2 Debugging
# -----------------
# - Show list of enabled sites: apache2ctl -S
# - Show list of enabled modules: apache2ctl -M
# - Show list of available modules: apache2ctl -l
# - Check syntax of configuration: apache2ctl -t
#
---
- name: Setup a zabbix server on a single host.
  hosts: zabbix_server
  become: true
  serial: 10
  roles:
    - role: geerlingguy.apache
      apache_remove_default_vhost: true
      apache_vhosts:
        - servername: status.zabbix-1.vagrant
          extra_parameters: |
            <location /server-status>
              SetHandler server-status
              Order deny,allow
              Deny from all
              Allow from 127.0.0.1
            </location>
    - role: geerlingguy.php
    - role: geerlingguy.postgresql
      postgresql_users:
        - name: zbx_monitor
          password: zabbixmonpass
    - role: community.zabbix.zabbix_server
      zabbix_server_dbname: zabbix
      zabbix_server_dbpassword_hash_method: scram-sha-256
      zabbix_server_dbpassword: zabbixdbpass
      zabbix_server_dbuser: zabbix
      zabbix_server_version: 7.0
    - role: community.zabbix.zabbix_web
      zabbix_api_server_url: www.zabbix-1.vagrant
      zabbix_server_database: pgsql
      zabbix_server_dbname: zabbix
      zabbix_server_dbpassword: zabbixdbpass
      zabbix_server_dbport: 5432
      zabbix_server_dbuser: zabbix
    - role: community.zabbix.zabbix_agent
      zabbix_agent_server: 127.0.0.1
      zabbix_agent_serveractive: 127.0.0.1
      zabbix_agent2: true
      zabbix_api_create_hostgroup: false
      zabbix_api_create_hosts: false
      zabbix_api_login_pass: zabbix
      zabbix_api_login_user: Admin
      zabbix_api_server_host: www.zabbix-1.vagrant
      zabbix_agent_tags:
        - tag: environment
          value: development
      zabbix_host_groups:
        - Linux servers
        - Zabbix servers
  tasks:
    - name: Set timezone.
      community.general.timezone:
        name: Europe/Berlin

    - name: Install zabbix agent2 plugins (Debian).
      ansible.builtin.apt:
        pkg:
          - zabbix-agent2-plugin-postgresql
      when: ansible_os_family == 'Debian'

    - name: Grant zbx_monitor user same permissions as pg_monitor.
      community.postgresql.postgresql_query:
        db: postgres
        query: GRANT pg_monitor TO zbx_monitor;
      become: true
      become_user: postgres
