# Zabbix Proxy Setup
#
# Firewall Configuration
# ----------------------
#   - Block IP: iptables -A INPUT -s [IP] -j DROP
#   - View Blocks: iptables -L -v
#   - Unblock IP: iptables -D INPUT -s [IP] -j DROP
---
- name: Setup a zabbix proxy.
  hosts: zabbix_proxy
  become: true
  roles:
    - role: geerlingguy.mysql
      mysql_users:
        - name: zabbix_proxy
          password: zabbix_proxy
    - role: community.zabbix.zabbix_proxy
      zabbix_proxy_server: zabbix-1.vagrant;zabbix-2.vagrant
      zabbix_api_server_host: zabbix-1.vagrant
      zabbix_api_login_user: Admin
      zabbix_api_login_pass: zabbix
      zabbix_api_create_proxy: false
      zabbix_proxy_name: '{{ inventory_hostname }}'
    - role: community.zabbix.zabbix_agent
      zabbix_agent_package_remove: true
      zabbix_agent_server: '{{ zabbix_agent_server_overwrite | default("zabbix-1.vagrant,zabbix-2.vagrant") }}'
      zabbix_agent_serveractive: '{{ zabbix_agent_serveractive_overwrite | default("zabbix-1.vagrant;zabbix-2.vagrant") }}'
      zabbix_agent2: true
      zabbix_api_create_hostgroup: false
      zabbix_api_create_hosts: false
      zabbix_api_login_pass: zabbix
      zabbix_api_login_user: Admin
      zabbix_api_server_host: zabbix-1.vagrant
      zabbix_agent_tags:
        - tag: environment
          value: development
