---
- name: Setup a zabbix agent.
  hosts: zabbix_agent
  become: true
  pre_tasks:
    - name: Install python dependencies for RedHat based systems.
      ansible.builtin.package:
        name: policycoreutils-python-utils
        state: present
      when: ansible_os_family == 'RedHat'
  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_agent_package_remove: true
      zabbix_agent_server: '{{ zabbix_agent_server_overwrite | default("zabbix-1.vagrant,zabbix-2.vagrant") }}'
      zabbix_agent_serveractive: '{{ zabbix_agent_serveractive_overwrite | default("zabbix-1.vagrant;zabbix-2.vagrant") }}'
      zabbix_agent2: true
      zabbix_api_create_hostgroup: false
      zabbix_api_create_hosts: false
      zabbix_api_login_pass: zabbix
      zabbix_api_login_user: Admin
      zabbix_api_server_host: zabbix-1.vagrant
      zabbix_host_groups:
        - Linux servers
      zabbix_agent_link_templates:
        - Linux by Zabbix agent
      zabbix_agent_tags:
        - tag: environment
          value: development
