---
- name: Base installation playbook
  hosts: all
  become: yes
  serial: 10
  tasks:
    - name: Include os specific variables
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      tags:
        - always

    - name: Include host configuration
      ansible.builtin.include_tasks: features/host_config.yml
      tags:
        - host

    - name: Include default toolchain
      ansible.builtin.include_tasks: features/default_toolchain.yml

    - name: Include host git packages
      ansible.builtin.include_tasks: features/host_git_packages.yml
      loop: "{{ h_git_packages | default([]) }}"
      tags:
        - host
