---
- name: Main ansible playbook
  hosts: all
  become: yes
  serial: 10
  tasks:
    - name: Include os specific variables
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      tags:
        - always

    # ---( Features )---

    - name: Include docker
      ansible.builtin.include_tasks: features/docker.yml
      when: feature_docker | default(false)
      tags:
        - docker

    - name: Include nginx
      ansible.builtin.include_tasks: features/nginx.yml
      when: feature_nginx | default(false)

    - name: Include traefik
      ansible.builtin.include_tasks: features/traefik.yml
      when: feature_traefik | default(false)
      tags:
        - application
        - traefik

    # ---( Applications )---

    - name: Include kimai
      ansible.builtin.include_tasks: applications/kimai.yml
      when:
        - app_kimai | default(false)
        - feature_docker | default(false)
        - (feature_nginx or feature_traefik) | default(false)
      tags:
        - application
        - kimai

    - name: Include loki
      ansible.builtin.include_tasks: applications/loki.yml
      when:
        - app_loki | default(false)
        - feature_docker | default(false)
        - (feature_nginx or feature_traefik) | default(false)
      tags:
        - application
        - loki

    - name: Include matrixhook
      ansible.builtin.include_tasks: applications/matrixhook.yml
      when:
        - app_matrixhook | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - matrixhook

    - name: Include nextcloud
      ansible.builtin.include_tasks: applications/nextcloud.yml
      when:
        - app_nextcloud | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - nextcloud

    - name: Include roundcube
      ansible.builtin.include_tasks: applications/roundcube.yml
      when:
        - app_roundcube | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - roundcube

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      tags:
        - application
        - nginx

    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
      tags:
        - docker

    - name: Restart loki
      community.docker.docker_compose:
        project_src: "{{ f_docker__home }}/loki"
        restarted: yes
      tags:
        - application
        - loki
