---
- name: Main ansible playbook
  hosts: all
  become: yes
  serial: 10
  tasks:
    - name: Include os specific variables
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"

    - name: Include host configuration
      ansible.builtin.include_tasks: features/host_config.yml
      tags:
        - host

    - name: Include default toolchain
      ansible.builtin.include_tasks: features/default_toolchain.yml

    # ---( Features )---

    - name: Include docker
      ansible.builtin.include_tasks: features/docker.yml
      when: feature_docker | default(false)

    - name: Include nginx
      ansible.builtin.include_tasks: features/nginx.yml
      when: feature_nginx | default(false)

    - name: Include traefik
      ansible.builtin.include_tasks: features/traefik.yml
      when: feature_traefik | default(false)
      tags:
        - application
        - traefik

    # ---( Applications )---

    - name: Include kimai
      ansible.builtin.include_tasks: applications/kimai.yml
      when:
        - app_kimai | default(false)
        - feature_docker | default(false)
        - (feature_nginx or feature_traefik) | default(false)
      tags:
        - application
        - kimai

    - name: Include nextcloud
      ansible.builtin.include_tasks: applications/nextcloud.yml
      when:
        - app_nextcloud | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - nextcloud

    - name: Include roundcube
      ansible.builtin.include_tasks: applications/roundcube.yml
      when:
        - app_roundcube | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - roundcube

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      tags:
        - application
        - nginx

    - name: Update kimai
      community.docker.docker_compose:
        project_src: "{{ f_docker__home }}/kimai"
      tags:
        - application
        - kimai

    - name: Update nextcloud
      community.docker.docker_compose:
        project_src: "{{ f_docker__home }}/nextcloud"
      tags:
        - application
        - nextcloud

    - name: Update roundcube
      community.docker.docker_compose:
        project_src: "{{ f_docker__home }}/roundcube"
      tags:
        - application
        - roundcube

    - name: Update traefik
      community.docker.docker_compose:
        project_src: "{{ f_docker__home }}/traefik"
      tags:
        - application
        - traefik
