---
- name: Configure servers
  hosts: servers
  become: yes
  serial: 10
  tasks:
    - name: Include os specific variables
      ansible.builtin.include_vars: '{{ item }}'
      with_first_found:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
      tags:
        - always

    # ---( Features )---

    - name: Import docker (Linux)
      ansible.builtin.import_tasks:
        file: features/docker_linux.yml
      when:
        - ansible_system == 'Linux'
        - feature_docker | default(false)
      tags:
        - docker

    - name: Import nginx (Linux)
      ansible.builtin.import_tasks:
        file: features/nginx.yml
      when:
        - ansible_system == 'Linux'
        - feature_nginx | default(false)
      tags:
        - application
        - nginx

    - name: Import traefik (Linux)
      ansible.builtin.import_tasks:
        file: features/traefik.yml
      when:
        - ansible_system == 'Linux'
        - feature_traefik | default(false)
      tags:
        - application
        - traefik

    # ---( Applications )---

    - name: Import kimai
      ansible.builtin.import_tasks:
        file: applications/kimai.yml
      when:
        - app_kimai | default(false)
        - feature_docker | default(false)
        - (feature_nginx | default(false) or feature_traefik | default(false))
      tags:
        - application
        - kimai

    - name: Import loki
      ansible.builtin.import_tasks:
        file: applications/loki.yml
      when:
        - app_loki | default(false)
        - feature_docker | default(false)
        - (feature_nginx | default(false) or feature_traefik | default(false))
      tags:
        - application
        - loki

    - name: Import matrixhook
      ansible.builtin.import_tasks:
        file: applications/matrixhook.yml
      when:
        - app_matrixhook | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - matrixhook

    - name: Import nextcloud
      ansible.builtin.import_tasks:
        file: applications/nextcloud.yml
      when:
        - app_nextcloud | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - nextcloud

    - name: Import roundcube
      ansible.builtin.import_tasks:
        file: applications/roundcube.yml
      when:
        - app_roundcube | default(false)
        - feature_docker | default(false)
        - feature_traefik | default(false)
      tags:
        - application
        - roundcube

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      tags:
        - application
        - nginx

    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
      tags:
        - docker

    - name: Restart loki
      community.docker.docker_compose:
        project_src: '{{ f_docker__home }}/loki'
        restarted: yes
      tags:
        - application
        - loki
