- hosts: sonarqube
  become: yes
  tasks:
  - name: Install ansible dependencies for postgres
    apt:
      name: python3-psycopg2

  - name: Run postgres role
    include_role:
      name: kevincoakley.postgres

  - name: Create sonarqube database
    postgresql_db:
      name: sonarqube
    become_user: postgres

  - name: Create sonarqube database user
    postgresql_user:
      db: sonarqube
      name: sonarqube
      password: sonarqube
      priv: "ALL"
      role_attr_flags: NOSUPERUSER,NOCREATEDB
    become_user: postgres

  - name: Run java role
    include_role:
      name: geerlingguy.java

  - name: Run sonarqube role
    include_role:
      name: lrk.sonarqube
