---
- name: Check if init has already been run.
  ansible.builtin.stat:
    path: '{{ init_ansible_cache_path }}/init.complete'
  register: __init_complete

- name: Ensure ansible cache directory exists.
  ansible.builtin.file:
    path: '{{ init_ansible_cache_path }}'
    state: directory
    mode: '0755'

- name: Update Package Cache (apt).
  tags: always
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false
  when:
    - ansible_pkg_mgr == 'apt'
    - not __init_complete.stat.exists

- name: Update Package Cache (yum).
  tags: always
  ansible.builtin.yum:
    update_cache: yes
  changed_when: false
  when:
    - ansible_pkg_mgr == 'yum'
    - not __init_complete.stat.exists

- name: Install required python packages.
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop: '{{ init_python_packages }}'
  when: not __init_complete.stat.exists

- name: Install required pip packages.
  ansible.builtin.pip:
    name: '{{ item }}'
    state: present
  loop: '{{ init_pip_packages }}'
  when: not __init_complete.stat.exists

- name: Mark init as complete.
  ansible.builtin.file:
    path: '{{ init_ansible_cache_path }}/init.complete'
    state: touch
    mode: '0644'
  when: not __init_complete.stat.exists
