---
- name: Install required python packages
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
    update_cache: true
    cache_valid_time: ' {{ apt_cache_valid_time | default("3600") }}'
  loop: '{{ init_python_packages }}'

- name: Install required pip packages
  ansible.builtin.pip:
    name: '{{ item }}'
    state: present
    break_system_packages: true
  loop: '{{ init_pip_packages }}'
