name: tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - role: common
            scenario: default
          - role: init
            scenario: default
          - role: pkg
            scenario: default
          - role: ssh
            scenario: default
          - role: ssh
            scenario: install
          - role: ssh
            scenario: uninstall
    steps:
      - uses: actions/checkout@v3
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_args: --scenario-name ${{ matrix.target.scenario }}
          molecule_working_dir: roles/${{ matrix.target.role }}

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Create ansible home directory
        run: |
          mkdir -p ~/.ansible

      - name: Cache ansible roles
        uses: actions/cache@v3
        with:
          path: ~/.ansible/roles
          key: ${{ runner.os }}-poetry-${{ hashFiles('requirements.yml') }}

      - name: Install ansible roles
        run: |
          ansible-galaxy install -r requirements.yml

      - name: Create vault file
        run: |
          echo "{{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ~/.ansible/chronicc-vault-pass

      - uses: pre-commit/action@v3.0.0
